# @package _global_
device: gpu

defaults:
  - /Run: default                         # Runtime settings
  - /Logger: default                      # Logging settings
  - /Model: load_model                    # Load model weights (can be pre-trained or checkpoint)
  - /System: ase_create                   # System initialization:
                                          #   'load_system': load pre-existing structure
                                          #   'ase_create': generate system using ASE
  - /Task: opt                            # Task type:
                                          #   'md' for molecular dynamics
                                          #   'opt' for optimization
  - /Calculator: ase                      # Calculator interface (ASE in this case)
  - override hydra/job_logging: disabled  # Disable Hydra's default job logging
  - _self_

hydra:
  job:
    name: optimizer_ase                  # Hydra job name (used in output directories)
    chdir: True                          # Change working directory to run.dir
  run:
    dir: ./out_${hydra:job.name}/${now:%Y%m%d_%H%M%S}  # Output directory
