_target_: ppmat.calculator.ase.OptimizationTask

optimizer: LBFGS            # Optimizer name
filter: FrechetCellFilter   # Filter name
fmax: 0.05                  # Maximum force tolerance
steps: 100                  # Number of steps
