Global:
  do_train: true
  do_eval: true
  do_test: Ture
  use_voxel: false
Trainer:
  max_epochs: 2000
  max_iter: 40000
  seed: 42
  output_dir: ./output/infgcn_omol25
  save_freq: 2000
  log_freq: 1000000
  start_eval_epoch: 0
  eval_freq: 1
  pretrained_model_path: null
  pretrained_weight_name: null
  resume_from_checkpoint: null
  use_amp: false
  amp_level: O1
  eval_with_no_grad: true
  gradient_accumulation_steps: 1
  best_metric_indicator: train_loss
  name_for_best_metric: loss
  greater_is_better: false
  compute_metric_during_train: true
  metric_strategy_during_eval: epoch
  use_visualdl: false
  use_wandb: false
  use_tensorboard: true
  out_dict:
    train:
    - loss
    eval:
    - mae
Model:
  __class_name__: InfGCN
  __init_params__:
    n_atom_type: 69
    num_radial: 32
    num_spherical: 7
    radial_embed_size: 32
    radial_hidden_size: 128
    num_radial_layer: 2
    num_gcn_layer: 3
    cutoff: 5.0
    grid_cutoff: 5.0
    is_fc: true
    gauss_start: 0.5
    gauss_end: 5.0
    activation: norm
    residual: true
    pbc: false

Optimizer:
  __class_name__: Adam
  __init_params__:
    lr:
      __class_name__: ReduceOnPlateau
      __init_params__:
        learning_rate: 0.001
        factor: 0.5
        patience: 10
        min_lr: 1.0e-05
        by_epoch: true
        indicator: eval_loss
        indicator_name: loss
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999

Dataset:
  train:
    dataset:
      __class_name__: DensityDataset
      __init_params__:
        root: ./data/dataset_OMol25_MC_5k
        split_file: omol25_debug10.json
        atom_file: ./data/dataset_OMol25_MC_5k/omol25.json
        extension: cube
        compression: lz4
        pbc: false
        split: train
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: false
        drop_last: false
        batch_size: 2
    loader:
      num_workers: 0
      use_shared_memory: false
      collate_fn: DensityCollator
      collate_params:
        n_samples: 2048
        sampling_mode: uniform
        uniform_random_offset: true
        sampling_seed: 42
        clip_max: 200.0
        importance_sampling: true
        importance_threshold: 1.0e-05
        importance_ratio: 0.6
        extreme_threshold: 100.0
        extreme_ratio: 0.05
  val:
    dataset:
      __class_name__: DensityDataset
      __init_params__:
        root: ./data/dataset_OMol25_MC_5k
        split_file: omol25_debug10.json
        atom_file: ./data/dataset_OMol25_MC_5k/omol25.json
        extension: cube
        compression: lz4
        pbc: false
        split: validation
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: false
        drop_last: false
        batch_size: 2
    loader:
      num_workers: 0
      use_shared_memory: false
      collate_fn: DensityCollator
      collate_params:
        n_samples: 2048
        sampling_mode: uniform
        uniform_random_offset: true
        sampling_seed: 42
        clip_max: 200.0
        importance_sampling: false
        importance_threshold: 1.0e-05
        importance_ratio: 0.6
        extreme_threshold: 100.0
        extreme_ratio: 0.05
  test:
    dataset:
      __class_name__: DensityDataset
      __init_params__:
        root: ./data/dataset_OMol25_MC_5k
        split_file: omol25_debug10.json
        atom_file: ./data/dataset_OMol25_MC_5k/omol25.json
        extension: cube
        compression: lz4
        pbc: false
        split: test
        rotate: false
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: false
        drop_last: false
        batch_size: 1
    loader:
      num_workers: 0
      use_shared_memory: false
      collate_fn: DensityCollator
      collate_params:
        n_samples: 2048
        sampling_mode: uniform
        uniform_random_offset: true
        sampling_seed: 42
        clip_max: 200.0
        importance_sampling: false
        importance_threshold: 1.0e-05
        importance_ratio: 0.6
        extreme_threshold: 100.0
        extreme_ratio: 0.05
